name: nexuspro
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Packages (Updated)
  firebase_core: ^3.12.1  # Latest version
  firebase_auth: ^5.5.1 
  firebase_storage: ^12.4.4
  firebase_database: ^11.3.4 # If using Firebase Auth
  cloud_firestore: ^5.6.5 # If using Firestore (remove if not needed)

  # State Management
  get: ^4.7.2

  # Other Packages
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  file_picker: ^9.2.3
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:  # <-- Correct indentation
    - assets/logo.png
    - assets/coc.jpeg
    - assets/genshin-impact-version-28_vf5v.1280.webp
    - assets/pubg-logo-background-6ldzn94r2bu0r668.jpg
    - assets/Warzone.jpeg
    - assets/GARENA1-1.webp
    - assets/Call-of-Duty-Victory-in-Match.jpg
    
    